### PR TITLE
Update Pg17 to RC1

### PR DESCRIPTION
**Pull request by thomasboussekey**

### CODE REVIEW

**Comment by ImreSamu** [comment]
Thank you for the PR!
( And please ignore the coderabbit comments. )

Unfortunately, the postgres:17rc1 Docker images don't exist yet,
so we can't test or run it.  Because of this, I will only be able to test it later.

see: https://hub.docker.com/_/postgres/tags?page_size=&ordering=&name=17rc1
* "No tags found ; This repository doesn't have any tags that have "17rc1" in their names."

**Comment by ImreSamu** [comment]
@thomasboussekey :
It seems like there's a merge conflict, with the message: 'This branch has conflicts that must be resolved.'
Please check if your changes include all the commits!   ( https://github.com/postgis/docker-postgis/commits/master/ )

Also, please:
* Use ['git mv' ("Move or rename a file, a directory, or a symlink")](https://git-scm.com/docs/git-mv)  to implement the update from `17beta3` to `17rc1`, 
   * `git mv 17beta3-master 17rc1-master`
   * `git mv 17beta3-3.5.0alpha2 17rc1-3.5.0alpha2`
* and only after that, run the `./update.sh`.
* As much as possible, manually update:
  *  `.github/workflows/main.yml`
       *  replace `17beta3` to `17rc1`
  * `README.md`
      * the `update.sh` generate some markdown text in the log;  need to replace in the relevant part of the README.md.
      * and update the "# Versions (2024-08-20)" - part, to the current iso date ->  "(2024-09-06)" ! 
      
Thank you in advance!

**Comment by thomasboussekey** [comment]
Closed by error, Unable to reopen it
Can you please help me @ImreSamu ?

**Comment by thomasboussekey** [comment]
reopen

**Comment by ImreSamu** [comment]
@thomasboussekey  

It seems I can't reopen the pull request because you may have deleted the 'bump_pg17rc1' branch 
(see "closed this by deleting the head repository"), 
and I don't have access to restore your repository.
image

At least, this branch no longer exists:
* https://github.com/thomasboussekey/docker-postgis/tree/bump_pg17rc1

So, either
* you restore the deleted branch and try to re-open, 
* or create a fresh new pull request and a new branch.

Or, if it's not urgent, I can create a new update pull request in the next few days.

**Pull request closed without merging**
