### PR TITLE
[SFCGAL] bump hash and use new gitlab url

### PR DESCRIPTION
**Pull request by lbartoletti**
Hash: Bump to latest version
Url: SFCGAL have now a dedicated group on gitlab

### CODE REVIEW

**Comment by phillipross** [comment]
@lbartoletti thanks for the contribution!
@ImreSamu This PR looks fine to me but can you give it look and make sure it's good to merge?

**Comment by ImreSamu** [comment]
@phillipross : 
looks OK.

**Non-critical comment:**
It appears that the two master Dockerfiles have been manually modified, as only the SFCGAL hash has been updated and the rest have not. 
If you can add an update generated by running `./update.sh` (as an extra commit), 
then we can be certain there won't be any issues with future updates.

**Comment by phillipross** [comment]
@ImreSamu good point, thanks!

@lbartoletti Did you understand the request?  Please run the `./update.sh` script in your branch and commit the results to make sure everything else is updated.  Thanks!

**Review by ImreSamu — APPROVED** [review]

**Comment by ImreSamu** [comment]
@phillipross : 
I have run the `./update.sh` command and committed the updates. 
I believe everything is fine. It's ready for merging! 
(Only the CircleCI test is not working right now; but I will try to fix that later, it's not causing any problems at the moment.)

@lbartoletti: Thank you for the pull request!

**Comment by lbartoletti** [comment]
Sorry, I was sick last week. 
Thanks for the hints and the update!

**Pull request merged**
