### PR TITLE
Postgres 12 + postgis 3

### PR DESCRIPTION
**Pull request by smellman**
Original PR: https://github.com/appropriate/docker-postgis/pull/151
The original PR may stopped so I rewrite PR.

### CODE REVIEW

**Comment by smellman** [comment]
This PR fail in `wget` command...

**Comment by smellman** [comment]
I added travis_retry command.

**Comment by phillipross** [comment]
Thanks @smellman 

We're in the process of transitioning the github and dockerhub repos to the postgis organization and verifying the pipelines still work, so please don't be alarmed if you see errors showing up in this PR.  We'll review it once we get the infrastructure changed ironed out.

**Comment by smellman** [comment]
I will re-write my PR after https://github.com/postgis/docker-postgis/pull/166 marged

**Comment by phillipross** [comment]
Thanks @smellman 

My first comment is that we'd like maintain a 2.5 and 3.x release both, as well as postgres 9, 10, 11, and 12.  The changes in your PR thus far, appear to replace postgis 2.5 with v3.0.

Also, I see changes to the update.sh script and the Dockerfiles, but no changes to the Dockerfile templates.  For now we'd like to keep the builds templatized and have the update.sh script process the templates and generate the Dockerfiles in the directories that would then be used to build the images.  I'm preparing changes to the script with PR #166 to make it possible to build postgis 2.5 and 3.0 both, but I won't create the directories for the 3.0.  I'd like to still give you the opportunity to rewrite this PR on top of PR #166 and create the 3.0 directories and wire them in so that you're counted as a contributor 😉 

In the meantime, please feel free to review and comment on PR #166 if you'd like.

**Comment by smellman** [comment]
@phillipross I started from original PR that remove postgis 2.5 (without postgres 9.5) and added 3.0.
I think this reason is they didn't remove [this line](https://github.com/postgis/docker-postgis/pull/166/files#diff-1578307c887a49e90a57418e653ad7f6L12).
This line is discussed in other issues but anyone remove it(but I and you remove it in PR).
I just add comment to #166 to fix wget issue that my PR happened.
I have no more comment and I will try build 3.0 images.
Also I close this PR because I will re-create using your branch.

**Pull request closed without merging**
