### PR TITLE
Alpine upgrade to 3.12 ; fix compile error ; update master, alpine

### PR DESCRIPTION
**Pull request by ImreSamu**
Upstream `postgres` alpine docker image  - upgraded to Alpine 3.12
*  https://github.com/docker-library/postgres/pull/742

changes in this PR:
* The `llvm9-dev`  changed to `llvm10-dev`  in the `Dockerfile.alpine.template`  ( based on the upstream changes )
*  *-alpine , *-master Dockerfiles updated  ( `./update.sh` )

probably this is fixing the current  .travis alpine errors :
*  https://travis-ci.org/github/postgis/docker-postgis/jobs/701487188 ` /usr/lib/llvm10/bin/llvm-lto: not found`

expected results:  all .travis check will be ok.

### CODE REVIEW

**Comment by phillipross** [comment]
Looks good... is it ready for merge?

**Comment by ImreSamu** [comment]
> is it ready for merge?

imho:  yes 
( I have not test too much )

**Comment by phillipross** [comment]
I built locally and all of my local test harnesses appear to work fine too 👍

**Comment by ImreSamu** [comment]
Thanks! 

and now the `postgis/postgis:13-master` is based on [ `PostgreSQL 13beta2`  released 25th June 2020](https://www.postgresql.org/about/news/2047/)
```
$ docker run --rm -it --link pg13:postgres \
>      postgis/postgis:13-master \
>      sh -c 'PGPASSWORD=mysecretpassword exec psql -h "$POSTGRES_PORT_5432_TCP_ADDR" -p "$POSTGRES_PORT_5432_TCP_PORT" -U postgres -c "SELECT version();"'
                                                             version                                                         
-------------------------------------------------------------------------------------------------------------------------
 PostgreSQL 13beta2 (Debian 13~beta2-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
(1 row)
```

**Comment by phillipross** [comment]
Great!  This means #195 can be closed?

**Comment by ImreSamu** [comment]
> This means #195 can be closed?

the `13-3.0`  is still missing.  ( debian + alpine ) 

imho: waiting for `postgresql-13-postgis-3`

```
$ docker run -it --rm  postgres:13 bash
root@caf8f8201016:/# apt-get update
Get:1 http://security.debian.org/debian-security buster/updates InRelease [65.4 kB]
Get:2 http://deb.debian.org/debian buster InRelease [121 kB]                                                 
Get:3 http://deb.debian.org/debian buster-updates InRelease [51.9 kB]                                                   
Get:4 http://apt.postgresql.org/pub/repos/apt buster-pgdg InRelease [84.6 kB]
Get:5 http://security.debian.org/debian-security buster/updates/main amd64 Packages [204 kB]
Get:6 http://deb.debian.org/debian buster/main amd64 Packages [7,905 kB]
Get:7 http://apt.postgresql.org/pub/repos/apt buster-pgdg/main amd64 Packages [177 kB]
Get:8 http://deb.debian.org/debian buster-updates/main amd64 Packages [7,868 B]
Get:9 http://apt.postgresql.org/pub/repos/apt buster-pgdg/13 amd64 Packages [7,765 B]     
Fetched 8,626 kB in 2s (3,743 kB/s)                        
Reading package lists... Done
root@caf8f8201016:/# apt-get install postgresql-13-postgis-3
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package postgresql-13-postgis-3
root@caf8f8201016:/# 
```

**Pull request merged**
