### PR TITLE
Reconnect after creating extension, to fix search_path race

### PR DESCRIPTION
**Pull request by strk**
Closes GH-288

@ImreSamu any issue with this ? It's a workaround, but seems effective

### CODE REVIEW

**Comment by ImreSamu** [comment]
@strk 
> any issue with this ? It's a workaround, but seems effective

:heavy_check_mark: 
Thanks for the fix;   It seems OK for me!

**Comment by strk** [comment]
There's a fix upstream, but won't be present in earlier versions of PostGIS, so this workaround might be still good to keep.
Upstream fix: https://git.osgeo.org/gitea/postgis/postgis/pulls/99

**Comment by strk** [comment]
Does the CI also check for *running* the docker image ? As this change will only affect running it, not building it

**Comment by ImreSamu** [comment]
@strk :

ouch ..sorry,
probably the `make update`  is missing ..  and now only just the template file is updated.

and the https://github.com/postgis/docker-postgis/blob/master/13-3.2/initdb-postgis.sh is the old version.

please create a new PR and run the `make update`

**Comment by ImreSamu** [comment]
I will create a new PR - with the "make update"

**Pull request merged**
