### PR TITLE
update to Postgis 3.2  (Postgis 3.1 deprecated)

### PR DESCRIPTION
**Pull request by ImreSamu**
* http://postgis.net/2021/12/18/postgis-3.2.0/
* https://www.postgresql.org/message-id/E1n02TN-0002NI-Jw%40atalia.postgresql.org "postgis updated to version 3.2.0+dfsg-1.pgdg+1"

Important changes:
*  `.github/workflows/main.yml`
*  `README.md`
*  `update.sh`

and 
*  `make update` outputs

### CODE REVIEW

**Comment by ImreSamu** [comment]
`13|14-master` Geos reverted for an older version  (2021dec16 - commits) 

Ready for review.

**Comment by phillipross** [comment]
This looks good to me.  Is it ready to merge?

**Comment by ImreSamu** [comment]
> This looks good to me. Is it ready to merge?

imho: yes.

---

In the next ~urgent PR ( probably this year ):  an Alpine upgrade to 3.15 is expected! 
-  reason:  the [upstream postgres:*-alpine3.14](https://hub.docker.com/_/postgres?tab=tags&page=1&name=alpine3.14) is not refreshing.

on the other hand, It is so complex
- because the alpine3.15 has a newer PROJ than PostGIS 2.5 can be used.
- and we don't have a ["jq template" solution like in the docker-library/postgres upstream](https://github.com/docker-library/postgres/blob/master/apply-templates.sh)

**Comment by phillipross** [comment]
@ImreSamu I think putting a jq-based templating system in place is really what will be necessary to provide a more elegant and maintainable way of building the images with their combinations of build architecture/platforms, OS variants, and combinations of pgsql+postgis+lib/dep releases and versions.

Is this something you'd be willing and able to work on?

**Comment by ImreSamu** [comment]
@phillipross :
 
in the next few months:   I don't have a plan/time to rewrite to "a jq-based templating system"; 
* so if you have time  - you can refactor this part.  

------

for an `alpine3.15` upgrade:  As I see  - we need to build an older GEOS / PROJ / GDAL version for the PostGIS 2.5
* Current  "ugly" status:  https://gist.github.com/ImreSamu/b8fecedf715a602e73630137533e20b5#file-dockerfile-alpine-template
  * I am still testing;  in the next few days I will try to create a temporary PR to discuss

**Comment by phillipross** [comment]
@ImreSamu That's fair if you don't have the time.  In recent months I've been thinking about how to do this and have some ideas, so I'll try to bootstrap it in some way.  For the most part, the best way to do it is to piggyback on what the postgres repo does, and extend it to include capabilities for specifying versions of postgis, gdal, geos, proj, et al.

I'll keep an eye out for your postgis 2.5 PR 😉

**Pull request merged**
