### PR TITLE
postgis 3.3.1 and 15beta4 upgrade ; remove postgis 2.5

### PR DESCRIPTION
**Pull request by ImreSamu**
Changes:
* Drop Debian Stretch as it's EOL  ( No Upstream update. https://github.com/docker-library/postgres/pull/974 )
  * --> removing all  postgis2.5 images. ( including 2.5-alpine )
     * Currently the alpine image is dependent on the debian version. In the future, this limitation should be removed with the next major planned refactoring ( ~ jq ) 
    
* Upgrade to Postgis 3.3.1
  * except `10-3.2` 
 
* upgrade to Postgres 15beta4
  * `15beta3-3.2`  -> `15beta4-3.3`
  * `15beta3-master` -> `15beta4-master`
 
* Removed test docker images:
   * `14-3.3.0rc2`
   * `15beta3-3.3.0rc2`
  
PR method:

```
# Remove Postgis 2.5 ( alpine, debian )
git rm -r 10-2.5/
git rm -r 11-2.5/

# Upgrade to 3.3
git mv 11-3.2/   11-3.3/  
git mv 12-3.2/   12-3.3/  
git mv 13-3.2/   13-3.3/  
git mv 14-3.2/   14-3.3/

# Removing test images
git rm -r 14-3.3.0rc2/ 
git rm -r 15beta3-3.3.0rc2/
git rm -r 15beta3-3.2/
git rm -r 15beta3-master/

# re-generate new docker files from template
make update
```

+ later re-Added:
- `15beta4-3.2`
- `15beta4-master` 

manual Upgrade :
* `README.md`
* `.github/workflows/main.yml`

Status:
* OLD:  21 JOB ( image )
* NEW: 15 JOB ( image )

### CODE REVIEW

**Comment by ImreSamu** [comment]
Status:
* OLD:  21 JOB ( image )
* NEW: 14 JOB ( image )

Ready to review / merge ;

**Comment by ImreSamu** [comment]
I have added 
* the last minute[ "2022-09-11 09:09:10: postgis updated to version 3.3.1+dfsg-1.pgdg+1"](https://www.postgresql.org/message-id/E1oXIxi-004J4E-8C%40atalia.postgresql.org)
* And I have to remove all `15beta3` test image 
   * related to  "SQL/JSON removed" fix https://trac.osgeo.org/postgis/ticket/5231
   
Ready to review|merge;

**Comment by ImreSamu** [comment]
I have re-added the new 15beta4-* images; 
so All the planned things are done.

Status:
* OLD: 21 JOB ( image )
* NEW: 15 JOB ( image )

cc: @phillipross ;  Ready to review ( Merge )

**Review by phillipross — APPROVED** [review]
lgtm

**Comment by phillipross** [comment]
a fond farewell to v2.5
thanks @ImreSamu !

**Pull request merged**
