### PR TITLE
add 13-master and update 12-master (#195)

### PR DESCRIPTION
**Pull request by ImreSamu**
* add 13-master
* update 12-master
* add 13-master to .travis

### CODE REVIEW

**Comment by ImreSamu** [comment]
ready for review

**Comment by ImreSamu** [comment]
expected version:
```sql
$ docker run --rm -it --link test13master:postgres \
>      postgis/postgis:13-master \
>      sh -c 'PGPASSWORD=mysecretpassword exec psql -h "$POSTGRES_PORT_5432_TCP_ADDR" -p "$POSTGRES_PORT_5432_TCP_PORT" -U postgres -c "SELECT PostGIS_Full_Version();"'
                                                                               postgis_full_version                                                                                
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 POSTGIS="3.1.0dev 16121bf" [EXTENSION] PGSQL="130" GEOS="3.9.0dev-CAPI-1.14.0" PROJ="7.1.0" LIBXML="2.9.4" LIBJSON="0.12.1" LIBPROTOBUF="1.3.1" WAGYU="0.5.0 (Internal)" TOPOLOGY
(1 row)
```

**Comment by phillipross** [comment]
looks good to me... is this ready to be merged?

**Comment by ImreSamu** [comment]
> is this ready to be merged?

yes ..
it is working for me .. ( and I have tested with my local project )


ps:
* probably other postgis users would like to test the new   `12-master` / `13-master` image ..  
      * imho: it would be a good idea to make a small anouncement about the testing possibility in the [postgis-users](https://lists.osgeo.org/pipermail/postgis-users/2020-May/date.html)  mail list :)

**Pull request merged**
