### PR TITLE
Update to PostGIS 3.5 debian

### PR DESCRIPTION
**Pull request by ImreSamu**
Changes:
- :new:  Updated `LATEST_VERSION` to `17-3.5`  ( Makefile )
- :new:  Set CGAL version to `master`  ( `Dockerfile.master.template`  , ./update.sh )
   -[SFCGAL 2.0](https://gitlab.com/sfcgal/SFCGAL/-/releases/v2.0.0) was released 4 days ago. In theory, there should be no compatibility issues between SFCGAL master and CGAL master.
- Renamed `1*-3.4` directories to `1*-3.5`
- Regenerated Dockerfiles from templates using `./update.sh`
- Updated CI configuration and README

Context: https://www.postgresql.org/message-id/E1t0NCG-000wPf-FN%40atalia.postgresql.org

### CODE REVIEW

**Comment by alanivey** [comment]
For what it's worth, these builds work for me: https://github.com/baosystems/docker-postgis/actions/runs/11337698871

**Comment by ImreSamu** [comment]
@alanivey:  Thank you for your test! 

-----------------

Ready to review;

The 17-master version ( from the CI log )
```
2024-10-15T01:52:20.2177414Z #21 0.284 + cat _pgis_full_version.txt
2024-10-15T01:52:20.2178834Z #21 0.284  PostgreSQL 17.0 (Debian 17.0-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
2024-10-15T01:52:20.2179993Z #21 0.284 
2024-10-15T01:52:20.2184169Z #21 0.284  POSTGIS="3.6.0dev 3.5.0-21-g77bcee793" [EXTENSION] PGSQL="170" GEOS="3.14.0dev-CAPI-1.20.0" SFCGAL="SFCGAL 2.0.0, CGAL 6.0.1, BOOST 1.74.0" PROJ="9.6.0 NETWORK_ENABLED=OFF URL_ENDPOINT=https://cdn.proj.org USER_WRITABLE_DIRECTORY=/var/lib/postgresql/.local/share/proj DATABASE_PATH=/usr/local/share/proj/proj.db" (compiled against PROJ 9.14.0) GDAL="GDAL 3.10.0dev-014581eece, released 2024/10/14" LIBXML="2.9.10" LIBJSON="0.15" LIBPROTOBUF="1.3.3" WAGYU="0.5.0 (Internal)" TOPOLOGY RASTER
```

**Comment by petetnt** [comment]
FWIW, I created https://github.com/postgis/docker-postgis/issues/396 to discuss a solution for having a bit more stable images.

**Review by phillipross — APPROVED** [review]
lgtm thanks!

**Pull request merged**
