### PR TITLE
fix199;  Oslandia/SFCGAL migrates to GitLab  + ./update.sh

### PR DESCRIPTION
**Pull request by ImreSamu**
Ready for review:
* fix https://github.com/postgis/docker-postgis/issues/199 "Oslandia/SFCGAL migrates from GitHub to GitLab"
* update  `12-master` ;  `13-master`

### CODE REVIEW

**Comment by ImreSamu** [comment]
the `13-master` looks ok

```select postgis_full_version();
                                                                               postgis_full_version                                                                                
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 POSTGIS="3.1.0dev 1fab20d" [EXTENSION] PGSQL="130" GEOS="3.9.0dev-CAPI-1.14.0" PROJ="7.2.0" LIBXML="2.9.4" LIBJSON="0.12.1" LIBPROTOBUF="1.3.1" WAGYU="0.5.0 (Internal)" TOPOLOGY
(1 row)

```

**Comment by ImreSamu** [comment]
the `12-master` looks ok
```
postgres=# select postgis_full_version();
                                                                               postgis_full_version                                                                                
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 POSTGIS="3.1.0dev 1fab20d" [EXTENSION] PGSQL="120" GEOS="3.9.0dev-CAPI-1.14.0" PROJ="7.2.0" LIBXML="2.9.4" LIBJSON="0.12.1" LIBPROTOBUF="1.3.1" WAGYU="0.5.0 (Internal)" TOPOLOGY
(1 row)
```

**Comment by ImreSamu** [comment]
* I have minimally tested ... it looks ok.
* ready for review

**Comment by phillipross** [comment]
looks good to me... is there anything more that these needs before being merged?

**Comment by ImreSamu** [comment]
@phillipross :
imho: you can merge ...

**Pull request merged**
