### PR TITLE
Dockerfile.master.template SFCGAL / PROJ refactoring.

### PR DESCRIPTION
**Pull request by ImreSamu**
UPDATED 2023-Feb-11:

PROPOSED CHANGES for the `Dockerfile.master.template`

- SFCGAL building  with  cgal 5.5.x-branch  +  header only build
"By utilizing the latest commit of the CGAL 5.5.x-branch and implementing a header-only build for SFCGAL,
 one can benefit from the latest CGAL patches while avoiding compatibility issues."
related: https://github.com/postgis/docker-postgis/discussions/335

- better GDAL building ( added more type )
 
- better logging / test / etc  ( internal, undocumented )
  - `/_pgis_full_version.txt`   PostGIS_Full_Version() contains the raster, sfcgal and topology versions.
  
- refresh PROJ data - workarounds: https://trac.osgeo.org/postgis/ticket/5316   ( +1MB docker image size )

MINOR changes 

-  added a warning for all templates : " NOTE: THIS DOCKERFILE IS GENERATED VIA "make update"! PLEASE DO NOT EDIT IT DIRECTLY"

-  added (master) : `LABEL org.opencontainers.image.source="https://github.com/postgis/docker-postgis"`
    * snyk proposal:  https://snyk.io/blog/how-and-when-to-use-docker-labels-oci-container-annotations/

- github checkout upgraded to "actions/checkout@v3"  ( avoid warnings )

- etc ...

SIZE increase:
* `postgis/postgis:15-master` image size increase from 555MB -> 567MB

HOW to test :
- Build the 15-master version in your local environment. ( `VARIANT=default VERSION=15-master make build` )
- check the size of the new image ( a little bigger )
- check the contents of `/_pgis_cgal_last_commit.txt`
- check the contents of `/_pgis_full_version.txt`
- check the `PostGIS_Full_Version()`
- test with your code ...
- If you managed to test it, please write a few lines about what you tested and how you tested it, to make our work easier.

### CODE REVIEW

**Comment by ImreSamu** [comment]
status:

#  `postgis/postgis:15-master` 

```
PostgreSQL 15.1 (Debian 15.1-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
POSTGIS="3.4.0dev 3.3.0rc2-420-g732064a15" [EXTENSION] 
  PGSQL="150" 
  GEOS="3.12.0dev-CAPI-1.18.0" 
  SFCGAL="SFCGAL 1.4.1, CGAL 5.5.2, BOOST 1.74.0" 
  PROJ="9.2.0" 
  GDAL="GDAL 3.7.0dev-437b59d300, released 2022/12/26" 
  LIBXML="2.9.10" 
  LIBJSON="0.15" 
  LIBPROTOBUF="1.3.3" 
  WAGYU="0.5.0 (Internal)" 
  TOPOLOGY 
  RASTER
```

  
* Image size  old: `555MB`  -->  new: `561MB`
* Build time: a little longer

**Comment by ImreSamu** [comment]
Dear @swiss-knight,

If you have the time, I would appreciate your comments on my proposal to solve the SFCGAL problem you raised.
It took me a little longer to get it done, so I apologize for that, but I ran into an unexpected problem with the `proj` data. 

If you have the time to test it, that would be even more helpful and it would also help to get the PR accepted sooner.

Since you have also made a proposal for a solution ( https://github.com/postgis/docker-postgis/pull/336  ), feel free to let me know if you think it is better, I am open to other solutions.

**Comment by ImreSamu** [comment]
status:
* `postgis/postgis:15-master` :  old size `555MB`  new:  `559MB`  ( +4 MB )

from a log ( https://github.com/postgis/docker-postgis/actions/runs/4144520723/jobs/7167671112 )

```
 PostgreSQL 15.1 (Debian 15.1-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit

 POSTGIS="3.4.0dev 3.3.0rc2-594-gb669712b3" [EXTENSION] PGSQL="150" GEOS="3.12.0dev-CAPI-1.18.0" SFCGAL="SFCGAL 1.4.1, CGAL 5.5.2, BOOST 1.74.0" PROJ="9.2.0" GDAL="GDAL 3.7.0dev-edbe20c8d8, released 2023/02/10" LIBXML="2.9.10" LIBJSON="0.15" LIBPROTOBUF="1.3.3" WAGYU="0.5.0 (Internal)" TOPOLOGY RASTER

 address_standardizer         | 3.4.0dev | public     | Used to parse an address into constituent elements. Generally used to support geocoding address normalization step.
 address_standardizer_data_us | 3.4.0dev | public     | Address Standardizer US dataset example
 fuzzystrmatch                | 1.1      | public     | determine similarities and distance between strings
 plpgsql                      | 1.0      | pg_catalog | PL/pgSQL procedural language
 postgis                      | 3.4.0dev | public     | PostGIS geometry and geography spatial types and functions
 postgis_raster               | 3.4.0dev | public     | PostGIS raster types and functions
 postgis_sfcgal               | 3.4.0dev | public     | PostGIS SFCGAL functions
 postgis_tiger_geocoder       | 3.4.0dev | tiger      | PostGIS tiger geocoder and reverse geocoder
 postgis_topology             | 3.4.0dev | topology   | PostGIS topology spatial types and functions

+ cat _pgis_full_version.txt
Removing intermediate container 91eef7c3aa78
 ---> b34b163031db
Successfully built b34b163031db
Successfully tagged postgis/postgis:15-master
docker images          postgis/postgis:15-master
REPOSITORY        TAG         IMAGE ID       CREATED        SIZE
postgis/postgis   15-master   b34b163031db   1 second ago   559MB
```

**Comment by ImreSamu** [comment]
```log
 PostgreSQL 15.2 (Debian 15.2-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
 POSTGIS="3.4.0dev 3.3.0rc2-601-gb1b8c11bf" [EXTENSION] PGSQL="150" GEOS="3.12.0dev-CAPI-1.18.0" SFCGAL="SFCGAL 1.4.1, CGAL 5.5.2, BOOST 1.74.0" PROJ="9.2.0" GDAL="GDAL 3.7.0dev-06d99ac634, released 2023/02/11" LIBXML="2.9.10" LIBJSON="0.15" LIBPROTOBUF="1.3.3" WAGYU="0.5.0 (Internal)" TOPOLOGY RASTER

 address_standardizer         | 3.4.0dev | public     | Used to parse an address into constituent elements. Generally used to support geocoding address normalization step.
 address_standardizer_data_us | 3.4.0dev | public     | Address Standardizer US dataset example
 fuzzystrmatch                | 1.1      | public     | determine similarities and distance between strings
 plpgsql                      | 1.0      | pg_catalog | PL/pgSQL procedural language
 postgis                      | 3.4.0dev | public     | PostGIS geometry and geography spatial types and functions
 postgis_raster               | 3.4.0dev | public     | PostGIS raster types and functions
 postgis_sfcgal               | 3.4.0dev | public     | PostGIS SFCGAL functions
 postgis_tiger_geocoder       | 3.4.0dev | tiger      | PostGIS tiger geocoder and reverse geocoder
 postgis_topology             | 3.4.0dev | topology   | PostGIS topology spatial types and functions

Removing intermediate container 766b0442a92c
 ---> 22f730739be5
Successfully built 22f730739be5
Successfully tagged postgis/postgis:15-master
docker images          postgis/postgis:15-master
REPOSITORY        TAG         IMAGE ID       CREATED        SIZE
postgis/postgis   15-master   22f730739be5   1 second ago   567MB
```

**Comment by ImreSamu** [comment]
@phillipross : 
Ready for review / merge ..

If you have any special requests or want certain things done differently or in a different PR, let me know and I'll change the PR.

**Review by phillipross — APPROVED** [review]
I think this all looks ok.

I think it's also safe to say that maintaining these master builds is often involving a great deal of non-trivial work.  Thanks for the  continued effort!

**Pull request merged**
