### PR TITLE
Prepare images for Postgres 12 / PostGIS 3.0.0

### PR DESCRIPTION
**Pull request by eyusupov**
This is based on https://github.com/appropriate/docker-postgis/pull/142.
proj is built with g++ and libstdc++ from edge, so the same version need
to be installed for it to work.

It compiles and runs, but I didn't test it thoroughly yet.
I'm going to try importing an OSM extract to test it.

### CODE REVIEW

**Comment by nyurik** [comment]
Great to see people work on it already!  Please note that without GEOS 3.8+ there is relatively little point in upgrading to PostGIS 3.0. See https://carto.com/blog/postgis-3-release/

**Comment by eyusupov** [comment]
Works fine so far with importing and rendring volga_fed_districts using openmaptiles stack.

**Comment by eyusupov** [comment]
Beware! I was setting up Nominatim and encountered this PG12 bug, a fix for which not been merged yet: https://www.postgresql.org/message-id/flat/20191004043021.ylfbxcjqyypphfft%40alap3.anarazel.de#c11dfd761fe0bdf9fc48436cc69aff62
Keep it in mind if you're planning to move to PG12.

**Comment by nyurik** [comment]
@eyusupov older GEOS will work, it just won't work as fast.  Also note that you may want to disable PostgreSQL JIT -- it has a bug when running complex queries, making them run 1000x times slower.  See https://www.postgresql.org/message-id/20191025010456.ubs2jdxdrb6td7m2%40alap3.anarazel.de

**Comment by ankurk91** [comment]
Not working for me.
* Mac OS 10.15
* Docker desktop 2.1 (engine 19)
```
git clone https://github.com/eyusupov/docker-postgis -b postgres-12-postgis-3 --single-branch --depth=1
cd docker-postgis/12-3
docker build .
```

getting this error
```
E: Version '3.0.0+dfsg-1.pgdg100+1' for 'postgresql-12-postgis-3' was not found
E: Version '3.0.0+dfsg-1.pgdg100+1' for 'postgresql-12-postgis-3-scripts' was not found
E: Version '3.0.0+dfsg-1.pgdg100+1' for 'postgis' was not found
```

**Comment by nyurik** [comment]
Another thing to be aware of -- there is a bug in PostGIS 3.0, making holes dissappear in complex geometries (e.g. natural earth's water polygons 50m would show up without New Zealand and a few other places).  This issue has been fixed in PostGIS master.

**Comment by torangel** [comment]
Results from my testing:

Windows 10
Docker desktop 2.1.0.5 (engine 19.03.5)

```
docker-postgis\12-3\docker build .
..loglines...
Reverse Provides:
Reading package lists...
Building dependency tree...
Reading state information...
E: Version '3.0.0+dfsg-1.pgdg100+1' for 'postgresql-12-postgis-3' was not found
E: Version '3.0.0+dfsg-1.pgdg100+1' for 'postgresql-12-postgis-3-scripts' was not found
E: Version '3.0.0+dfsg-1.pgdg100+1' for 'postgis' was not found
```

**docker-postgis\12-3\alpine**
```
docker-postgis\12-3\alpine [postgres-12-postgis-3 ≡]> docker build -t tc_postgres12:alpine .
--success
docker run tc_postgres12:alpine

===========log===============
The files belonging to this database system will be owned by user "postgres".                                                                                                  
This user must also own the server process.                                                                                                                                    
                                                                                                                                                                               
The database cluster will be initialized with locale "en_US.utf8".                                                                                                             
The default database encoding has accordingly been set to "UTF8".                                                                                                              
The default text search configuration will be set to "english".                                                                                                                
                                                                                                                                                                               
Data page checksums are disabled.                                                                                                                                              
                                                                                                                                                                               
fixing permissions on existing directory /var/lib/postgresql/data ... ok                                                                                                       
creating subdirectories ... ok                                                                                                                                                 
selecting dynamic shared memory implementation ... posix                                                                                                                       
selecting default max_connections ... 100                                                                                                                                      
selecting default shared_buffers ... 128MB                                                                                                                                     
selecting default time zone ... UTC                                                                                                                                            
creating configuration files ... ok                                                                                                                                            
running bootstrap script ... ok                                                                                                                                                
performing post-bootstrap initialization ... sh: locale: not found                                                                                                             
2019-11-20 10:23:41.544 UTC [29] WARNING:  no usable system locales were found                                                                                                 
ok                                                                                                                                                                             
syncing data to disk ... ok                                                                                                                                                    
                                                                                                                                                                               
                                                                                                                                                                               
Success. You can now start the database server using:                                                                                                                          
                                                                                                                                                                               
    pg_ctl -D /var/lib/postgresql/data -l logfile start                                                                                                                        
                                                                                                                                                                               
initdb: warning: enabling "trust" authentication for local connections                                                                                                         
You can change this by editing pg_hba.conf or using the option -A, or                                                                                                          
--auth-local and --auth-host, the next time you run initdb.                                                                                                                    
waiting for server to start....2019-11-20 10:23:42.012 UTC [34] LOG:  starting PostgreSQL 12.1 on x86_64-pc-linux-musl, compiled by gcc (Alpine 8.3.0) 8.3.0, 64-bit           
2019-11-20 10:23:42.015 UTC [34] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"                                                                            
2019-11-20 10:23:42.034 UTC [35] LOG:  database system was shut down at 2019-11-20 10:23:41 UTC                                                                                
2019-11-20 10:23:42.040 UTC [34] LOG:  database system is ready to accept connections                                                                                          
 done                                                                                                                                                                          
server started                                                                                                                                                                 
                                                                                                                                                                               
/usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/postgis.sh                                                                                            
/usr/local/bin/docker-entrypoint.sh: /docker-entrypoint-initdb.d/postgis.sh: /bin/sh^M: bad interpreter: No such file or directory                                        
```

For alpine the build of the image is ok, but it fails on run (see two last loglines)

Thought this might had something to do with unix/windows file-endings. Tried therefore changing the line endings on the "postgis.sh" file from CRLF to LF, which resulted in
```/docker-entrypoint-initdb.d/postgis.sh: line 13: syntax error: bad substitution```

I then changed to initdb-postgis.sh to this: (which works)
```
#!/bin/sh

set -e

echo "testing script"

# Perform all actions as $POSTGRES_USER
export PGUSER="$POSTGRES_USER"

# Create the 'template_postgis' template db

psql --dbname="$DB" -c "CREATE DATABASE template_postgis;"
psql --dbname="$DB" -c "UPDATE pg_database SET datistemplate = TRUE WHERE datname = 'template_postgis';"

# Load PostGIS into both template_database and $POSTGRES_DB
for DB in template_postgis "$POSTGRES_DB"; do
	echo "Loading PostGIS extensions into $DB"
	psql --dbname="$DB" -c "
		CREATE EXTENSION IF NOT EXISTS postgis;
		CREATE EXTENSION IF NOT EXISTS postgis_raster;
		CREATE EXTENSION IF NOT EXISTS postgis_topology;
		CREATE EXTENSION IF NOT EXISTS fuzzystrmatch;
		CREATE EXTENSION IF NOT EXISTS postgis_tiger_geocoder;
		"

done
```

**Comment by eyusupov** [comment]
@torangel I don't have a windows machine to reproduce. Are you getting successful build on the master branch?

**Comment by torangel** [comment]
## 1- Confirmation
@eyusupov . Obviously the 12-3 does not exist in the master branch (if I understood your question correct), but I can confirm the same problem relies in the master branch as well for the 
```
docker-postgis\11-2.5 [master ≡]> docker build -t testimage .
---logs---
Reading state information...
E: Version '2.5.2+dfsg-1~exp1.pgdg90+1' for 'postgresql-11-postgis-2.5' was not found
E: Version '2.5.2+dfsg-1~exp1.pgdg90+1' for 'postgresql-11-postgis-2.5-scripts' was not found
E: Version '2.5.2+dfsg-1~exp1.pgdg90+1' for 'postgis' was not found
```

## 2-Failing alpine (because of packages?`)
I have now done another try on building the 12-3 alpine image, but what previously worked just fine now failes with the following errormessage:
```
+ apk add --no-cache --virtual .build-deps-edge --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing --repository http://dl-cdn.alpinelinux.org/alpine/edge/main g++ gdal-dev geos-dev proj-dev protobuf-c-dev
fetch http://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  gdal-dev (missing):
    required by: .build-deps-edge-20191127.182403[gdal-dev]
  geos-dev (missing):
    required by: .build-deps-edge-20191127.182403[geos-dev]
  proj-dev (missing):
    required by: .build-deps-edge-20191127.182403[proj-dev]
```
I notice that the build-deps-edge is ```build-deps-edge-20191127.171719``` compared to ```20191122.143637``` which worked at my build-server last week

I am not deeply into the APK and gdal, but it looks to me as if something has changed in the package repository? Any advice on how to handle this is greatly appreciated.

**Comment by smellman** [comment]
> Not working for me.
> 
>     * Mac OS 10.15
> 
>     * Docker desktop 2.1 (engine 19)
> 
> 
> ```
> git clone https://github.com/eyusupov/docker-postgis -b postgres-12-postgis-3 --single-branch --depth=1
> cd docker-postgis/12-3
> docker build .
> ```
> 
> getting this error
> 
> ```
> E: Version '3.0.0+dfsg-1.pgdg100+1' for 'postgresql-12-postgis-3' was not found
> E: Version '3.0.0+dfsg-1.pgdg100+1' for 'postgresql-12-postgis-3-scripts' was not found
> E: Version '3.0.0+dfsg-1.pgdg100+1' for 'postgis' was not found
> ```
> 
> P.S. - Alpine worked fine

I work with changing value: `ENV POSTGIS_VERSION 3.0.0+dfsg-2~exp1.pgdg100+1` 

https://apt.postgresql.org/pub/repos/apt/pool/main/p/postgis/
Old package may removed.

**Comment by eyusupov** [comment]
Updated debian package version and rebased it on latest master

**Comment by torangel** [comment]
I can confirm @eyusupov 's change now is building succesfully on 
Windows 10
Docker desktop 2.1.0.5 (engine 19.03.5)

12-3/alpine however still fails with the message:
```
+ apk add --no-cache --virtual .build-deps-edge --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing --repository http://dl-cdn.alpinelinux.org/alpine/edge/main g++ gdal-dev geos-dev proj-dev protobuf-c-dev
fetch http://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  gdal-dev (missing):
    required by: .build-deps-edge-20191205.115320[gdal-dev]
  geos-dev (missing):
    required by: .build-deps-edge-20191205.115320[geos-dev]
  proj-dev (missing):
    required by: .build-deps-edge-20191205.115320[proj-dev]
```
I cannot find the gdal package in the edge/testing repo. I however can find it in
```http://dl-cdn.alpinelinux.org/alpine/edge/community/aarch64/```

When trying using this repo the build continues, but fails on ```cannot find /usr/bin/clang``` later in the build

**Comment by eyusupov** [comment]
Replaced testing repo with community and added clang dep for Alpine images

**Comment by eyusupov** [comment]
Adding gcc or clang package did not help, will investigate further

**Comment by frodrigo** [comment]
Postgres 12 image build fails with:
```
/usr/bin/clang -Wno-ignored-attributes -fno-strict-aliasing -fwrapv -O2  -I../liblwgeom -std=gnu99 -g -O2 -fno-math-errno -fno-signed-zeros -I../libpgcommon -I../deps/wagyu -I../deps/uthash/include  -I/usr/include   -I/usr/include/libxml2  -I/usr/include/json-c     -fPIC -DPIC -I. -I./ -I/usr/local/include/postgresql/server -I/usr/local/include/postgresql/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -flto=thin -emit-llvm -c -o postgis_module.bc postgis_module.c
make[1]: /usr/bin/clang: Command not found
make[1]: *** [/usr/local/lib/postgresql/pgxs/src/makefiles/../../src/Makefile.global:1044: postgis_module.bc] Error 127
make[1]: Leaving directory '/usr/src/postgis/postgis'
make: *** [GNUmakefile:20: all] Error 1
```

**Comment by d3mon187** [comment]
Hey guys!  I'm in testing and trying to get a world building server running as quickly as possible.  Still trying to figure everything out though.  I am currently using a modified version below of eyusupov/postgis-osm running the latest version of everything.  Noticed you're also working on a Alpine version.  Is there a significant difference between the two?  I finally got pg12 running quickly with the git=off suggestion, so thanks for that.  Are there any other openmaptiles pieces that are being worked on for speed?  Thanks! 

```
ARG POSTGRES_MAJOR=12
ARG POSTGIS_MAJOR=3
ARG OSML10N_VER=2.5.8

FROM postgres:${POSTGRES_MAJOR} AS builder

ARG POSTGRES_MAJOR
ARG POSTGIS_MAJOR
ARG OSML10N_VER

USER root

# Compile mapnik
RUN apt-get update \
   && apt-get install -y postgresql-server-dev-${POSTGRES_MAJOR} devscripts equivs git cmake sqlite3

ADD https://github.com/giggls/mapnik-german-l10n/archive/v${OSML10N_VER}.tar.gz /tmp/mapnik-german-l10n.tar.gz

RUN cd /tmp \
   && tar xvf mapnik-german-l10n.tar.gz \
   && cd mapnik-german-l10n-${OSML10N_VER} \
   && cat debian/control \
   && DEBIAN_FRONTEND=noninteractive mk-build-deps -ir -t "apt-get -qq --no-install-recommends" debian/control \
   && PG_SUPPORTED_VERSIONS=${POSTGRES_MAJOR} make deb

# Build gdal with PG 12 support
WORKDIR /tmp/build

RUN echo "deb-src http://deb.debian.org/debian buster main" >> /etc/apt/sources.list

RUN apt-get update && apt -y build-dep gdal-bin

RUN git clone https://github.com/OSGeo/proj.4.git /opt/proj.4
RUN cd /opt/proj.4/ && ls && ./autogen.sh && ./configure --prefix=/usr/local && make && make install
RUN git clone --single-branch --branch release/3.0 https://github.com/OSGeo/gdal.git
RUN cd gdal/gdal && ls && CXXFLAGS=-I/usr/local/include LDFLAGS=-L/usr/local/lib ./configure --with-proj=/usr/local --without-libtool && make && make install DESTDIR=/tmp/gdal

RUN cd /tmp/ && ls

RUN mkdir /tmp/deb && \
    mv /tmp/postgresql-${POSTGRES_MAJOR}-osml10n_2.5.7_$(dpkg --print-architecture).deb \
       /tmp/deb

FROM postgres:${POSTGRES_MAJOR}

MAINTAINER "Lukas Martinelli <me@lukasmartinelli.ch>"

ARG POSTGRES_MAJOR
ARG POSTGIS_MAJOR
ARG OSML10N_VER=2.5.8

COPY --from=builder /tmp/deb /tmp/deb
COPY --from=builder /tmp/gdal/ /
RUN apt-get update \
   && apt-get install -y postgresql-${POSTGRES_MAJOR}-postgis-${POSTGIS_MAJOR} /tmp/deb/* \
   && rm -rf /var/lib/apt/lists/*

ENV PROJSO libproj.so.13

COPY ./initdb-postgis.sh /docker-entrypoint-initdb.d/10_postgis.sh

```

**Comment by smellman** [comment]
@eyusupov I think we wait to build new docker images includes [This PR](https://github.com/docker-library/postgres/pull/657) for alpine.

The current postgres image build with alpine v3.10 and llvm8 but the `edge` or `v3.11` alpine packages and `clang` depends on `llvm9`.
Also v3.10 doesn't include gdal and some depends libraries.

I built postgres image as `smellman/postgres:12-alpine` and following can build docker image.
https://github.com/smellman/docker-postgis/commit/80af2955a8f1979c2d13ebcd5e06586463772668
Also I remove `edge`.

**Comment by torangel** [comment]
@smellman 

I tried building from 
https://github.com/smellman/docker-postgis.git
https://github.com/smellman/docker-postgis/commit/80af2955a8f1979c2d13ebcd5e06586463772668?diff=split



But was faced with this error/log
```
C:\kode\thirdparty\docker-postgis\12-3\alpine [(80af295...)]> docker build -t postgres .
Sending build context to Docker daemon  7.168kB
Step 1/6 : FROM postgres:12-alpine
 ---> c8abd8e13a5c
Step 2/6 : ENV POSTGIS_VERSION 3.0.0
 ---> Using cache
 ---> fc8079c8d978
Step 3/6 : ENV POSTGIS_SHA256 1c83fb2fc8870d36ed49859c49a12c8c4c8ae8c5c3f912a21a951c5bcc249123
 ---> Using cache
 ---> 9514af3da36e
Step 4/6 : RUN set -ex         && apk add --no-cache --virtual .fetch-deps         ca-certificates         openssl         tar         && wget -O postgis.tar.gz "https://github.com/postgis/postgis/archive/$POSTGIS_VERSION.tar.gz"     && echo "$POSTGIS_SHA256 *postgis.tar.gz" | sha256sum -c -     && mkdir -p /usr/src/postgis     && tar         --extract         --file postgis.tar.gz         --directory /usr/src/postgis         --strip-components 1     && rm postgis.tar.gz         && apk add --no-cache --virtual .build-deps         autoconf         automake         file         json-c-dev         libtool         libxml2-dev         make         perl         clang-dev         g++         gcc         gdal-dev         geos-dev         llvm9-dev         proj-dev         protobuf-c-dev     && cd /usr/src/postgis     && ./autogen.sh     && ./configure     && make     && make install     && apk add --no-cache --virtual .postgis-rundeps         json-c
    geos         gdal         proj         libstdc++         protobuf-c     && cd /     && rm -rf /usr/src/postgis     && apk del .fetch-deps .build-deps
 ---> Running in 6eb46247c6bc
+ apk add --no-cache --virtual .fetch-deps ca-certificates openssl tar
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/community/x86_64/APKINDEX.tar.gz
(1/4) Installing ca-certificates (20190108-r0)
(2/4) Installing openssl (1.1.1d-r2)
(3/4) Installing tar (1.32-r0)
(4/4) Installing .fetch-deps (20200107.120216)
Executing busybox-1.30.1-r2.trigger
Executing ca-certificates-20190108-r0.trigger
OK: 105 MiB in 37 packages
+ wget -O postgis.tar.gz https://github.com/postgis/postgis/archive/3.0.0.tar.gz
Connecting to github.com (140.82.118.3:443)
Connecting to codeload.github.com (140.82.113.9:443)
postgis.tar.gz        10% |***                             | 1734k  0:00:08 ETA
postgis.tar.gz        52% |****************                | 8614k  0:00:01 ETA
postgis.tar.gz       100% |********************************| 15.9M  0:00:00 ETA
+ sha256sum -c -
+ echo '1c83fb2fc8870d36ed49859c49a12c8c4c8ae8c5c3f912a21a951c5bcc249123 *postgis.tar.gz'
postgis.tar.gz: OK
+ mkdir -p /usr/src/postgis
+ tar --extract --file postgis.tar.gz --directory /usr/src/postgis --strip-components 1
+ rm postgis.tar.gz
+ apk add --no-cache --virtual .build-deps autoconf automake file json-c-dev libtool libxml2-dev make perl clang-dev g++ gcc gdal-dev geos-dev llvm9-dev proj-dev protobuf-c-dev
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  gdal-dev (missing):
    required by: .build-deps-20200107.120220[gdal-dev]
  geos-dev (missing):
    required by: .build-deps-20200107.120220[geos-dev]
  llvm9-dev (missing):
    required by: .build-deps-20200107.120220[llvm9-dev]
  proj-dev (missing):
    required by: .build-deps-20200107.120220[proj-dev]
The command '/bin/sh -c set -ex         && apk add --no-cache --virtual .fetch-deps         ca-certificates         openssl         tar         && wget -O postgis.tar.gz "https://github.com/postgis/postgis/archive/$POSTGIS_VERSION.tar.gz"     && echo "$POSTGIS_SHA256 *postgis.tar.gz" | sha256sum -c -     && mkdir -p /usr/src/postgis     && tar         --extract         --file postgis.tar.gz         --directory /usr/src/postgis         --strip-components 1     && rm postgis.tar.gz         && apk add --no-cache --virtual .build-deps         autoconf         automake         file         json-c-dev         libtool         libxml2-dev
       make         perl         clang-dev         g++         gcc         gdal-dev         geos-dev         llvm9-dev         proj-dev         protobuf-c-dev     && cd /usr/src/postgis     && ./autogen.sh     && ./configure     && make     && make install     && apk add --no-cache --virtual .postgis-rundeps         json-c         geos         gdal         proj         libstdc++         protobuf-c     && cd /     && rm -rf /usr/src/postgis     && apk del .fetch-deps .build-deps' returned a non-zero code: 5
```

Something obvious I am doing wrong?
(Windows 10: Docker version 19.03.5, build 633a0ea)

**Comment by smellman** [comment]
@torangel 
We need to wait upgrade postgres:12-alpine
I mentioned it.
If you want test it, let’s use smellman/postgres:12-alpine image in FROM.

**Comment by smellman** [comment]
@eyusupov I finished my work for your PR.
- [postgres PR](https://github.com/docker-library/postgres/pull/657) was merged and current postgres alpine images are alpine v3.11 based now.
- PostgreSQL 12 debian image is buster based so I modify update.sh to support buster
- Run update.sh to fix all changed

**Comment by smellman** [comment]
Also I fixes bug in postgres2.4-postgis2.5 now.

**Comment by phillipross** [comment]
I think we no longer need this PR since master branch now has postgis 2.5 and 3.0 building on postgresql 9.5 through 12.  We should close this PR and open issues and pull requests against the updated code on the master branch.  Thanks for helping with this!

**Pull request closed without merging**
