### PR TITLE
make update : 2020Aug18

### PR DESCRIPTION
**Pull request by ImreSamu**
`make update`
*  2020/08/15 :  https://postgis.net/2020/08/15/postgis-patches/ PostGis 2.5.5 ; 3.0.2

### CODE REVIEW

**Comment by phillipross** [comment]
looks good to me, thanks!  please let me know if this is ready to merge as is.

**Comment by ImreSamu** [comment]
you can merge ... 

disclaimer:  I don't have time to the deeper local test.  I hope it is OK.

**Comment by phillipross** [comment]
Honestly this change is so straightforward that it's only a packaging issue on docker's part... any problems will be postgis release's fault 😆  If there are problems the docker packages can easily be reverted

**Comment by ImreSamu** [comment]
> Honestly this change is so straightforward 

agree :) 
Let's go!

**Pull request merged**
