### PR TITLE
Remove Postgres 10 and support for older debian/postgis versions

### PR DESCRIPTION
**Pull request by BryanQuigley**
Postgres 10 is EOL (https://www.postgresql.org/support/versioning/)
This also drops mention of postgis 2.5 and older debian versions.

### CODE REVIEW

**Comment by phillipross** [comment]
@BryanQuigley thanks for the contribution!
@ImreSamu i'm inclined to push through the removal of v10+v2.5 since they are EOL and the existing dockerhub images for those versions won't be removed.  Do you see any problem with this?

**Comment by ImreSamu** [comment]
@BryanQuigley :  Thank you!

-  **Please** also update the `README.md` file, as I see this is not updated.
    - update the "date" in the "Versions ( 2022-11-14 )"
    - remove the 2 docker images ( 10-3.2 alpine and debian )
    - Search for the other: '10' ...
    
-  (recommended) Test the `make update`  and push the changes. 
    - in theory, only the `14-master/Dockerfile` and `15-master/Dockerfile` has been changed.


@phillipross: 

> Do you see any problem with this?

* The latest bullseye updated ~2 days ago ( https://hub.docker.com/_/debian/tags?page=1&name=bulls )
* The Docker Postgres upstream removed the PG10  ~2 days ago:  https://github.com/docker-library/postgres/pull/1011
     * so no security fixes; or any other updates in the base `postgres:10` docker images.
* The latest `postgis/postgis:10-3.2` updated ~ 1 days ago :heavy_check_mark:  ( https://hub.docker.com/r/postgis/postgis/tags?page=1&name=10-3.2 ) 
* **in this case we can remove it now ..**
   * but in similar cases, it is worth waiting +1/+2 weeks ( ~ next scheduled Monday generation )
     
**light proposal/suggestion:**
  
Please keep the alpine 2.5 generation  ( in the  [`Dockerfile.alpine.template`](https://github.com/postgis/docker-postgis/blob/master/Dockerfile.alpine.template) )  for  ~ +3 months / or the next significant alpine template refactoring
  *  Reason:  (maybe) it is useful for creating special "local" test images for the fresh PostGIS 2.5.9  ( [released: Nov 12, 2022](http://postgis.net/2022/11/12/postgis-2.5.9-eol/) )
  * But if someone really wants to refactor it, I won't stop them.

**Comment by BryanQuigley** [comment]
Thanks! Updated README and ran make update.sh but kept that as a separate commit.

Did not notice that alpine still had some 2.5 support, I'm in no rush to remove it :).

**Comment by ImreSamu** [comment]
@BryanQuigley : Thank you!  Looks good to me.

**Pull request merged**
